import localFont from "next/font/local";
import "./globals.css";
import BottomBar from "./components/BottomBar";
import Navbar from "./components/Navbar";
import { GlobalStateProvider } from "@/context/GlobalStateContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "My Anime Diary",
  description: "Generated by create next app",
  icon: "/logo-circular.png",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Fredoka:wght@300..700&display=swap" rel="stylesheet" />
        <link rel="shortcut icon" href="/logo-circular.png" type="image/png" />
        <script src="https://accounts.google.com/gsi/client" async defer></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased fredoka-font`}
      >
        <GlobalStateProvider>
          <Navbar />
          {children}
          <BottomBar />
        </GlobalStateProvider>
      </body>
    </html>
  );
}
